apiVersion: ENC[AES256_GCM,data:iOI=,iv:9pNiiFQ2mO1pK6+j3tTSjCYu0RcuqYIM06mg1Mw5qoA=,tag:AdK/JOWgrAv9JHXAJxS1Fg==,type:str]
kind: ENC[AES256_GCM,data:oEn61ZdP,iv:wqhCA+Hx5wmm4c/kCbJQ6Hhz7lp2lhoPY9cyR9kiKKY=,tag:1mjhVhmxGrZJ0ZM7YxrKuQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KZyJnPdebPbcjgXXDcZI,iv:u8YR7GlHSow9Jjv2CazS2h+AKciKH9imSUFs+n7uEy0=,tag:DCsvp8hjB2rS6kXQPxW3Zw==,type:str]
    namespace: ENC[AES256_GCM,data:OlhBqk8vIw==,iv:Db9kzGTMp0RDD1nNL0i2KHzhWwq5FIKEPLqNXCFIOec=,tag:mLHIoyeEIgjJAtboiHGIxw==,type:str]
type: ENC[AES256_GCM,data:NmTcVy/L,iv:yjpvLvJP6PNTRESYcZJJd2VCB4SZgT3qe5Gr7YDK64o=,tag:q7SuLkhE3a56eAxkFsZ60Q==,type:str]
stringData:
    jackett-api-key: ENC[AES256_GCM,data:FWS0kYSnAoFCTTQMg/ckQlw0CVl09IP6aF7xWrg/rEU=,iv://NF+CXm59f7DSqUrFRPyqzkfTY1ctmlnvJ33Lcz2wg=,tag:SgcIQeqLdNMonZ+OFk0aLw==,type:str]
    omdb-api-key: ENC[AES256_GCM,data:kp/XIXPxtxc=,iv:1UV4bTQXEvzXHDGqFop59sq3xU6k3Lh/zxsG+8l55as=,tag:4r9qpr88NDrqBwEKYFxhXw==,type:str]
sops:
    age:
        - recipient: age1axv9zypv86yn6z9n0jx80lwxe29kv6m6upp5tqz7wkyagt3fze3qm3ad2k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5T2lmUVg2WTBLWE5KaW1Y
            V2FoTzdNOU1xUlgvWGRWUnJNSEowakxzREU4ClUzcGF2WTZDSVk3dWd5VWNyUk83
            OHI4OFFYclFyOVVMbDIrd3p4TEVlWTgKLS0tIFlCYjRWcW00d3lqeFBPYXVHbVJo
            UHgvdDc0cFVVUXBFUzRmSXcveHRuTFkKY+yJNqqBhug5gB1ZzJI1CkP6jRd3bz0r
            3MytbFkBqyV4koROlQnRWAKsoOTiyf45RvUhxaahhPX78QrbWYqYXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T00:41:33Z"
    mac: ENC[AES256_GCM,data:gAGiCHMz8J3OxqndN5CLTFsIpNEorv8IJWGJCpF/J+vtKqO4XZw/ekhjAjZwRzWuZmnaaj5CGqwXU2CCSvyy97V6M0hLTR8cjYbbrCbf8UMnquIePGVBh2WU/6AdBisK9/KNRa0EukJ3aWp/tSc7Q3bv3A44k47nhKxjObyKxvQ=,iv:ZiGgl5r3424InT0AUd1xl4Fz1ENN6i0u/P0IzRqw2ko=,tag:kj1Kf8xxfp8xdAGoGDhZ4w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
