apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  namespace: anytype
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-03-30T23:36:12Z"
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: ghcr.io/anyproto/any-sync-node:latest
        command:
        - /usr/bin/any-sync-node
        args:
        - "-c"
        - "/etc/any-sync-node/config.yml"
        ports:
        - name: drpc-tcp
          containerPort: 33011
          hostPort: 33011
          protocol: TCP
        - name: drpc-udp
          containerPort: 33021
          hostPort: 33021
          protocol: UDP
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: config
          mountPath: /etc/any-sync-node
        - name: storage
          mountPath: /storage
      volumes:
      - name: config
        secret:
          secretName: anytype-configs
          items:
          - key: any-sync-node.yml
            path: config.yml
      - name: storage
        persistentVolumeClaim:
          claimName: node-storage
