apiVersion: ENC[AES256_GCM,data:BRM=,iv:2DR7SnOavFYZ7NDqOPS6pP944dv2H+h8fPyTudLUxJk=,tag:JRF+lfu/3W/VB4u5lhOjnA==,type:str]
kind: ENC[AES256_GCM,data:0g/9EiYs,iv:65ZDGkGrf6b2DFb8WWiXkCtjb+aaZCubpNMQrteLxLU=,tag:3cNclB5UcN5Yy5agT4Yi+A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:89bkfk8yx4z6I37Eg5OM+Fl6,iv:qFjAI4Zc13wSEyUZRG/LYVIp93zDAH2U/oGV1ItXg78=,tag:c8wdX1WM9cc7bNZnDlSSzQ==,type:str]
type: ENC[AES256_GCM,data:mSdlYT7T,iv:lWNFeKRXOxJEJUnO6Yw+z467djmfq23BapfybCk7oxw=,tag:ta2lTKALi20GUGOd2u+yhQ==,type:str]
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:bLj5Lgs7Y5ZHwuisVpCsjdnGsMVxR3o5Wuw=,iv:T8OlSSJnyiAh9FFgezrDnws0k4iP+pBHFVyEuJwaOeE=,tag:OvnB8/E3lQlvfumhs0wQtQ==,type:str]
sops:
    age:
        - recipient: age1axv9zypv86yn6z9n0jx80lwxe29kv6m6upp5tqz7wkyagt3fze3qm3ad2k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcUdaRXFnTzBBZm5WYUtG
            Tzc3bVBkejRXdkMvZTVjbGFwVVMvL1doNFhZClQxb3daQVQvTGFJY0NrYmZRS0ZC
            cWxXR1YralRNbXIzOVAxdlZ3eG1Ka1UKLS0tIDJCYWt6eXlOVG16NHlLS1VMc1BN
            NCtJODhyOWFPVmdsNVdnOWN1M1FMTUEK6GFxNnaB4ms2/8wKau73tq+sRdgaksfW
            HziaRIeGM9Ta2tjun4gB3HtjrM4VrejJfksiq0qJsmWmaM+gUUr+Sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T18:01:26Z"
    mac: ENC[AES256_GCM,data:j7Pic3ndRRYFCuSglrah3JUTptSK362DpmKfgCp4kZHputr8L2KN7AV1pIlDsZbI05nN0PmECWlLH0CON8Acs8tUUbKt1BkRZwIedB0IFg8MwTZqfh4e9En5Hd7kv60pmhZKy6VZAfSs5KjZbeHWIeIpZEAbUDcGX5zmJWKmxYU=,iv:BBXrxLthjsGVfPZ8OpjqHyj9IcSeGnrjh76w27xKS9k=,tag:HzwtVHz2/SVGc5djAv4ytg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
