apiVersion: ENC[AES256_GCM,data:bLY=,iv:31ZDK5xz0SziIIsB7nY9CPIfd1WWMZuXMNIaeDjOuos=,tag:ViG4Uz0HF7EoxxtiflDBFA==,type:str]
kind: ENC[AES256_GCM,data:gFwRvVRb,iv:VwoL/SIjWRmpa1olZpcsjD6kTFbubYwzQKsfvw1seX4=,tag:qVQmkfaSLPxyDIzJnxl8tQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZW1rAHyhccfS7fVUgXyyrw==,iv:OzbKUx0w2XsKP8QGtme39cdn9fYPhhM0Yw2RlBHe78o=,tag:b6jxgdymauE174vvRphkXA==,type:str]
type: ENC[AES256_GCM,data:GCWJEC9M,iv:GFO/SJ9XbpwVTn4F2HxJrsztedYXJj2FtmcWkhDJZkU=,tag:cv7b84zkTqOvF7S+r5URuA==,type:str]
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:oauoK6MTuJ9cBOeWaAuW+mIhjgRZJrG1XNyBPA==,iv:la2tEqV5SmWBjwmoh99O15YeXue8gWgJ5nSIBKaaDrE=,tag:i34+Atdj3nCwAoljxS+wqg==,type:str]
sops:
    age:
        - recipient: age1pt664fmp99xzkj22kt5argq5078txhfgaq2v7gmtnxtwk59n39lqdxxp09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRG42a09HRU9XVTVWUnVR
            Uk45SGgxZmV4cnd0SFkrcVVGdUhVR3ZIdTJZCnozODAralN4WGdhbXdwV1ozZXJN
            bnRRTEwyVHc2eStzQmEvOGRReWU0U0kKLS0tIE1YQ3lvbUwwSjduME9jbGNaYUZU
            V1c4UUx3cTllTjRUV0V3RkZIL3JBNkkK0qDX6KDLreCP/99vMZExkGXdoRtdJC9I
            1aXXzMhIB/uWZVcpV1Ih7Zo0mVVHNql9aEPFvx0fkvlVd67vaTe+4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T12:59:36Z"
    mac: ENC[AES256_GCM,data:GYh74xZE4oOcdkzk1EXDlvXPQ9lnvwlU5IcvliUlKG7XRYqBdgjSZYex2F7YgYaHbO/eN0caqoQ9/kVpNDki2TN0932Q42Q6eh704EmFm4BwbbW71/wUq5nLFymrwjLA9JJHnJiHUPkwEuSc/I0Vhk+k5Jkykfg19ePVyWNrDUw=,iv:Rphs+Rw6v1ZlGGSPam4NPkRnNs8si4SHEsTikVM9ZWw=,tag:cQybsVlt74pwXtzmdYovtw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2