apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  template:
    spec:
      initContainers:
        - name: install-ksops
          image: viaductai/ksops:v4.3.2 # Imagem que contém o binário
          command: ["cp", "/usr/local/bin/ksops", "/custom-tools/ksops"]
          volumeMounts:
            - name: custom-tools
              mountPath: /custom-tools
      containers:
        - name: argocd-repo-server
          env:
            - name: XDG_CONFIG_HOME
              value: /app/config
            - name: SOPS_AGE_KEY_FILE
              value: /app/config/sops/age/key.txt
          volumeMounts:
            - name: custom-tools
              mountPath: /usr/local/bin/ksops
              subPath: ksops
            - name: sops-age-key
              mountPath: /app/config/sops/age
              readOnly: true
      volumes:
        - name: custom-tools
          emptyDir: {}
        - name: sops-age-key
          secret:
            secretName: sops-age-key