apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-config
  namespace: minecraft
data:
  EULA: "TRUE"
  TYPE: "VANILLA"
  VERSION: "1.21.11"
  MEMORY: "8G"
  JVM_OPTS: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200"
  MOTD: "A Minecraft Server"
  MAX_PLAYERS: "10"
  DIFFICULTY: "normal"
  ONLINE_MODE: "TRUE"
  ENABLE_RCON: "true"
  OVERRIDE_SERVER_PROPERTIES: "TRUE"
