apiVersion: ENC[AES256_GCM,data:fGM=,iv:NuVmb5k4Fj5ePxtxNN0udg0EuYeTyNaIfEtGz0lxtj0=,tag:AHnxEysMgIxNGTVBBeMWwg==,type:str]
kind: ENC[AES256_GCM,data:1iiFa4CD,iv:13VdBIXY07AN3m0EgdPthk3QdZzjITSwDan6MmS/TPI=,tag:6mrLn3oe8BqobvZJGKPVkg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SMfFgDfAf4CRW1ff+V5S6Y4=,iv:vIgMU4PzxFt9CMgUO1LXZ7ailoBa+Dv+QUF/Yaidf/g=,tag:q1hNVJUebmbFaX1yOJ4EnA==,type:str]
    namespace: ENC[AES256_GCM,data:Eun83FvFkhS0,iv:kT2yGebJ3GvDU4sQiUecoWNuPC0DP0PKe50PJzumXf8=,tag:1MEJZx5ixkAwlpJI3/Xbug==,type:str]
type: ENC[AES256_GCM,data:yFF8IIMc,iv:UHoey4pBBEuBSCqdMpYdKywTW1xqSN4YFiEAC0CEWXs=,tag:0G1F4PC42sF+7MDiXZYJNw==,type:str]
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:5EeJVbYs1AiFWw==,iv:XUMV4apg3itn40GA581AYW8u/5vpezlTXfKDwr3u9m8=,tag:gVFtZ0DQ3sA1qBvPNp0feA==,type:str]
sops:
    age:
        - recipient: age1axv9zypv86yn6z9n0jx80lwxe29kv6m6upp5tqz7wkyagt3fze3qm3ad2k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQSszZEp0V2FDSFVqbTVj
            WnF2b2xzemlsUjRwREQ2d0ZrSVhaWjZXdWx3CnBlTFJoTko5T1RiQjVYV1F0NEtR
            WW1WeU1xNlJ6cjhxN1FVZ0dXQ1MzdDgKLS0tIHpGbHBBeVFsTjQxS2UrY3FlYkhh
            MnB5b2ZmYjRYRWJ4Zng2SERNVFF6TDAK7UWFu2rHJDLS6V/XqiLQO4ZZCN6uBbxb
            Hq9v+/Go36OLPCbYfL+L82Gz7lGVAWsvdMC70hBYcvmN5mLe9RqpIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T18:20:37Z"
    mac: ENC[AES256_GCM,data:PLfVko5DsqyuSSOa0ha3vSTxF+K5smQxr2bZ7zQKpAltrBTxYRqiTe3Ygv4xbAB6gXYYl5CWxh9Qh3OQx5SqrJmSby2r0cjZB/8VBPngV37S3EzNEewF7lObugo6eODDvzDxaTowtSr5zcrzt2kBQjbZWz/OOQb+ZvF+Wveev2U=,iv:QVz7A4m3gvfe4TUpLyepGXP1pr7eduxaQwTTPclPauU=,tag:M8f2/S38lFFXMkI8LG8UpA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
